version: 2
updates:
  - package-ecosystem: "npm"  # Use 'npm' for Node.js projects (or 'yarn' if you're using Yarn)
    directory: "/"  # Root directory where package.json is located
    schedule:
      interval: "monthly"  # Frequency of the updates (can also be "daily", "monthly", etc.)
